### ISSUE TITLE
Add EFI boot support

### ISSUE THREAD

**Issue by Bluerise** [bitrig/bitrig#10]
What's probably needed:

- [ ] EFI (FAT32) partition for (boot)loaders
- [ ] UEFI-compatible bootloader
- [ ] cdrom-image with EFI partition and loader(?)
- [ ] GPT support in the MBR bootloader for older systems
- [x] GPT support for partition table parsing
- [ ] some kernel internals we don't know yet

Some links:
- https://wiki.freebsd.org/UEFI
- http://svnweb.freebsd.org/base/projects/uefi/sys/boot/efi/

**Comment by kusuriya** [comment]
Looks like OpenBSD has its own EFI shell now, the only work that needs to be done to it is some porting of the inteldrm module to work in EFI, it might be worthwhile to pull it from upstream

**Comment by Bluerise** [comment]
Yup, basically syncing this in would make it done.

**Comment by Bluerise** [comment]
Since I'm not involved with the project anymore, I guess I can close this issue.
