### ISSUE TITLE
Unable to get a DHCP lease with msk0 (from reboot, works with cold boot though)

### ISSUE THREAD

**Issue by somasis** [bitrig/bitrig#25]
Works fine on Arch Linux, and latest OpenBSD-stable, however. Fails on Bitrig with the most recent snapshot as of writing.

Marvell 88E8040 PCI-E Fast Ethernet Controller.

**Comment by 4mig4** [comment]
Is it still relevant ?

**Comment by Bluerise** [comment]
Looks like it isn't, closing.
