### ISSUE TITLE
Marvell Armada 370 / XP support

### ISSUE THREAD

**Issue by Bluerise** [bitrig/bitrig#64]
Scaleway's C1 is based on a Marvell Armada 370 SoC. To support this, some code needs to be written. This is needed for #65.

* [x] FDT-based clock support
* [x] Clocks
* [x] Timer
* [x] Interrupt controller
* [x] UART
* [x] MBus
* [x] Gigabit Ethernet controller (needs fine tuning)
* [x] MDIO bus (for pbox, not c1)
* [x] SD-card
 * [x] SDMMC DMA + high speed + more
* [x] L2 Cache
* [x] Watchdog (needs testing)
* [x] extract console speed from bootargs
* [x] compare and check cache functions with Net- and FreeBSD
* [x] Putting it into the tree
* [x] ...

Dmesg: http://ix.io/ieW

**Comment by Bluerise** [comment]
Current state of code is tracked in branch [patrick_marvell](https://github.com/bitrig/bitrig/compare/patrick_marvell)

**Comment by moul** [comment]
Subscribing, I also can help

**Comment by Bluerise** [comment]
The fundamental code for interrupts, timers, clocks are written and will be tested once the development board arrives at my door. If those things work (and are verified to), EHCI and SD might just work right away.

Realistically this will need some debugging, "printf testing", and won't just work out of the box. If it really does work out of the box, I have done something wrong. :)

**Comment by Bluerise** [comment]
After getting the machine running and having a dtb I was able to start testing. I have been hitting a few tiny things that I ironed out, but all in all it has been good progress.

Now I hit a bigger road block. Apparently the processor does not support NEON/SIMD instructions, which our programs are optimized (by clang) to use. Now we will need to downgrade the default FPU to the VFP3, similar to what NetBSD uses. It's not perfect, but it's ok.

**Comment by Bluerise** [comment]
Still hanging on that issue. Hope to have it resolved soon.

**Comment by Bluerise** [comment]
Progress. ramdisk now is without NEON, only VFP3. console driver has been fixed up, replaced by the generic com(4) driver. timecounter is fixed. interrupts seem to work. sd cards seem to work out of the box.

**Comment by Bluerise** [comment]
I have linked a dmesg in the issue description.

**Comment by Bluerise** [comment]
Working on the ethernet controller right now. It's quite big, quite a mess, but I'm closing in.

Apart from some initialization bits and phy handling many parts should be ready now, like TX/RX handling. Some error handling can be improved though, and checksumming.

Testing and tuning this will take quite while...

**Comment by Bluerise** [comment]
Apparently I can now receive packets, but not send them.

It knows it got packets, the descriptor index actually changes, but it doesn't say that it has send a single packet. Weird.

**Comment by Bluerise** [comment]
Fixed the issue, it's working rather fine now. Though, it looks like it got hiccups on the local network. Maybe it's too fast. Gonna debug that.

**Comment by Bluerise** [comment]
Looks good now. We'll need to test it in the fixed-link setup now and make sure that works, too. Furthermore there are two other things to take care of.

First, we the cache flush functions don't seem reliable. After importing NetBSD's, it behaves a lot more sane. I need to compare Net-, FreeBSD and Bitrigs implementation and make it right.

Also the enabling the L2 cache controller makes the system very very unstable. I need to debug this. For now we can run with L2 disabled, but it'd really be much better to have this.

Also we will need to extract the baud rate somehow. This can either be done by crafting a new dtb especially for Bitrig (I don't like that much) or trying to parse the bootargs that were actually written for Linux (not beautiful, but probably works).

**Comment by Bluerise** [comment]
Baud rate can now be set to 9600 via bootargs by using "9" as an arg. L2 is still disabled, but other caches are now fixed. The marvell stuff hits the tree when the fixed-link setup at Scaleway works.

**Comment by Bluerise** [comment]
All things necessary are now put into the tree. fixed-link at Scaleway works, so there's nothing big left of important.

Another ToDo are proper L2 cache and SMP, but this is now a bit lower on the priority list.
