### ISSUE TITLE
Scaleway platform support

### ISSUE THREAD

**Issue by Bluerise** [bitrig/bitrig#65]
Scaleway provides cloud machines based on ARMv7 chips. Those are based on the Marvell Armada 370. They have 18 SoCs per blade, 16 blades per chassis. Thus 288 SoCs / 1152 cores per chassis. The modules themselves do not have integrated storage, but instead get / via a network block device (NBD).

* [x] Support the Marvell SoC (#64) (in progess)
* [x] Kernel support for NBD
* [x] xNBD client port
 * [x] port compiles
 * [x] remove Linux-ism
* [x] pivot_root
* [ ] initrd that takes care of bootup, dhcp, / attachment

**Comment by moul** [comment]
Subscribing

**Comment by Bluerise** [comment]
Took a day to make this work, but I have a working kernel side implementation for NBD. I believe there still are a few rough edges, but the biggest issues have been ironed out.

I can currently run NBD on a virtualized ARM platform. It's awesome.

**Comment by moul** [comment]
:beers:

**Comment by Bluerise** [comment]
xNBD seems to work, too. I had to rip out a few Linux specific things, but it seems to work now. I have a ramdisk with xNBD and curl to test the setup.

**Comment by moul** [comment]
I'm preparing you an admin access on u-boot so you can try to develop the `fixed-phy` driver

**Comment by Bluerise** [comment]
Now that the fixed-phy driver is fixed and we can theoretically install on /dev/nbd0a or so we need to somehow be able to make it / after booting up to the ramdisk and setting up NBD.

Now there are kind of three ways to make this work.

* chroot: More a hack, doesn't work well.
* xNBD kernel support: you need to know ip addresses and ports on bootup.
* pivot_root: not that easy to implement, but there's existing code.

Even though xNBD might be the easier way for us, the more proper way is pivot_root. Having this could also enable other opportunities.

**Comment by Bluerise** [comment]
pivot_root and NBD kernel support headed to master now. Time to cook another snap.

**Comment by 4mig4** [comment]
How is this moving forward ?

**Comment by moul** [comment]
Bitrig runs on Scaleway, I have multiple servers with Bitrig running :)
I didn't finished the rootfs and initrd preparation, I think I need about 1-2 more working days to get something nicely integrated with our actual image system

However, we are currently out-of-stock for the C1 servers, see: https://blog.scaleway.com/2015/11/03/scaleway-is-growing-too-fast-out-of-stock/
So it won't be the appropriate moment to release this, I fear

----

About the Bitrig support, I think the most important subject to work on will be about the multi-processor support

**Comment by kiike** [comment]
@moul, any news about the progress on integrating the Bitrig system into Scaleway? With the recent new availability of the C2 nodes it'd be good to get Bitrig onto them :).

**Comment by kiike** [comment]
@moul, any news about the progress on integrating the Bitrig system into Scaleway? With the recent new availability of the C2 nodes it'd be good to get Bitrig onto them :).

**Comment by moul** [comment]
Hi @kiike, it's on my todo list, I hope to get a beta image at the end of the month

**Comment by Bluerise** [comment]
Since I'm not involved with the project anymore, I guess I can close this issue.
