### ISSUE TITLE
PKG_PATH should be set by default to the current snapshot

### ISSUE THREAD

**Issue by yonas** [bitrig/bitrig#69]
I installed using http://mirror2.us.bitrig.org/pub/bitrig/snapshots/amd64/20150929/cd10.iso but PKG_PATH isn't set:

```
# echo $PKG_PATH

# uname -a
Bitrig bitrig.my.domain 1.0 GENERIC#0 amd64

# echo $SHELL
/bin/ksh
```

**Comment by 4mig4** [comment]
Is this still relevant ?

**Comment by jcvernaleo** [comment]
As drahn pointed out in bitrig-ports#72 this has been fixed so I'm closing.
