### ISSUE TITLE
Predefined C preprocessor macro for operating system detection

### ISSUE THREAD

**Issue by user1911431** [bitrig/bitrig#72]
Does Bitrig define a preprocessor macro to help detect the operating system in C or C++ source files? I am writing cross-platform C library and I would like to be able to detect if my code is being compiled on Bitrig. I couldn't find any documentation for this online unfortunately.

I have been using the following resource for figuring out how to detect operating systems: https://sourceforge.net/p/predef/wiki/OperatingSystems/

**Comment by marcopeereboom** [comment]
__Bitrig__

**Comment by user1911431** [comment]
Thanks, I will try to get this preprocessor compiler macro for Bitrig added to that [list](https://sourceforge.net/p/predef/wiki/OperatingSystems/) (I sent the mailing list an e-mail).

**Comment by preetpalS** [comment]
`__Bitrig__` appears to have become __Bitrig__ due to markdown styling.
