### ISSUE TITLE
iso is broken.

### ISSUE THREAD

**Issue by Unixware** [bitrig/bitrig#73]
No way to install from latest iso (install10.iso) as packages are broken
xshare10.tgz   / xfont10.tgz / xserv10.tgz . error: 'gzip stdin: unrecognised file format

**Comment by jcvernaleo** [comment]
Is the instal10.iso you are installing the one from http://mirror2.us.bitrig.org/pub/bitrig/snapshots/amd64/current/ (which is the 20160511 one)?
And where did you install the sets from?  http or something else?  I know I've installed with that iso and the sets from http without issue.  I just installed those same sets using the usb image two or three days ago and the sets were fine.  I spot checked them and the sets all look like perfect good gzip files so I think I need a little more info to look into this more.

**Comment by Unixware** [comment]
Thx, seems issue with the iso file on the mirror at [http://bitrig.antarctica.no/pub/bitrig/snapshots/amd64/current/](url)
